CREATE OR REPLACE VIEW order_history_lines_clean AS
SELECT
-- ORDER NUMBER INFO
    CAST(ORDLF_KEY AS UNSIGNED) AS ORDLF_KEY,
    CAST(ORDLF_ORDH_KEY AS UNSIGNED) AS ORDLF_ORDH_KEY,
    CAST(ORDL_ORDER_NO AS UNSIGNED) AS ORDL_ORDER_NO,
    CAST(ORDL_SUB_ORDER_NO AS UNSIGNED) AS ORDL_SUB_ORDER_NO,
    CAST(ORDL_SEQ_NO AS UNSIGNED) AS ORDL_SEQ_NO,
    CAST(ORDL_PARENT_SEQ_NO AS UNSIGNED) AS ORDL_PARENT_SEQ_NO,

-- ITEM NUMBER AND DESCTIPTION INFO AND CLEAN UP
    TRIM(ORDL_ITEM_NO) AS ORDL_ITEM_NO,
    CAST(LEFT(TRIM(ORDL_ITEM_NO), 2) AS UNSIGNED) AS ITEM_CLASS_NO,
    STRIP_DIGITS(TRIM(ORDL_ITEM_NO)) AS ORDL_ITEM_NO_SUFF,
    TRIM(ORDL_ITEM_DESC) AS ORDL_ITEM_DESC,
    SUBSTRING_INDEX(TRIM(ORDL_ITEM_DESC), ' ', 1) AS ORDL_ITEM_CLASS_NAME,

    -- QUANTITY, REVENUE, COST, AND PROFIT
    CAST(ORDL_ORDER_QTY AS UNSIGNED) AS ORDL_ORDER_QTY,
    CAST(ORDL_ITEM_PRICE AS DECIMAL(10,2)) AS ORDL_ITEM_REV,
    CAST(ORDL_ITEM_COST AS DECIMAL(10,2)) AS ORDL_ITEM_COST,
    CAST(ORDL_EXT_AMT AS DECIMAL(10,2)) AS ORDL_TOTAL_REV,
    CAST(ORDL_EXT_COST AS DECIMAL(10,2)) AS ORDL_TOTAL_COST,
    CAST(ORDL_EXT_AMT - ORDL_EXT_COST AS DECIMAL(10,2)) AS ORDL_TOTAL_PROFIT,
    CAST(ORDL_CONV_FACTOR AS DECIMAL(10,2)) AS ORDL_CONV_FACTOR,

-- ITEM LOCATIONS, MEASUREMENTS, ETC
    TRIM(ORDL_ITEM_UOM) AS ORDL_ITEM_UOM,
    TRIM(ORDL_ITEM_BIN) AS ORDL_ITEM_BIN,
    CAST(ORDL_PRICE_CD AS UNSIGNED) AS ORDL_PRICE_CD,
    CAST(ORDL_ITEM_CLASS AS UNSIGNED) AS ORDL_ITEM_CLASS,
    CAST(ORDL_WHSE_NO AS UNSIGNED) AS ORDL_WHSE_NO,

-- CUSTOMER & VENDOR INFO
    TRIM(ORDL_LOT_NO) AS ORDL_LOT_NO,
    TRIM(ORDL_CUST_NO) AS ORDL_CUST_NO,
    TRIM(ORDL_VENDOR) AS ORDL_VENDOR,

-- VMI AND SKID TAG
    CAST(ORDL_VMIT_TAG_NO AS UNSIGNED) AS ORDL_VMIT_TAG_NO,
    CAST(ORDL_SKID_TAG_NO AS UNSIGNED) AS ORDL_SKID_TAG_NO

FROM order_history_lines
WHERE TRIM(ORDL_ITEM_NO) NOT IN (
    'C', 'F', 'EXPORT', '1', 'x', 'X',
    'S', 'D', 'TAXABLE', 'NON-TAXABLE', 'T'
)
AND ORDL_ITEM_DESC NOT IN (
    '******* CREDIT MEMO ********',
    '____________________________'
)
HAVING ORDL_ITEM_NO_SUFF NOT IN (
    'DROP', 'TOLL', 'TUBE', 'SCRAP', 'REJECT', 'PIPE', 'PLATE',
    'M', 'FP', 'FLPLATE', 'DECK', 'CHAN', 'BEAM', 'BAR', 'ANG'
)
AND ORDL_ITEM_CLASS_NAME NOT IN ('ALMZ', 'ADJUSTMENT', 'ALZM', 
                                 'MISCELLANEOUS', 'PTD', 'BOND', 'PL', 
                                 'FLPL', 'AZ50', 'EG', 'GA/GI', 
                                 'SCRAP', 'GF', 'CLEAT', 'POTP', 
                                 'POTLDRY', 'SEC', '4', '5',''
)
AND ITEM_CLASS_NO BETWEEN 12 AND 67;


