CREATE OR REPLACE VIEW order_history_hdrs_clean AS
SELECT
-- Order Identifiers
    ORDHF_KEY,
    CAST(ORDH_ORDER_NO AS UNSIGNED) AS ORDH_ORDER_NO,
    CAST(ORDH_SUB_ORDER_NO AS UNSIGNED) AS ORDH_SUB_ORDER_NO,

-- Order Amounts, Revenues, and Profits
    CAST(ORDH_GROSS_AMT AS DECIMAL(10,2)) AS ORDH_GROSS_AMT,
    CAST(ORDH_SPCHG_AMT AS DECIMAL(10,2)) AS ORDH_SPCHG_AMT,
    CAST(ORDH_FREIGHT_AMT AS DECIMAL(10,2)) AS ORDH_FREIGHT_AMT,
    CAST(ORDH_TAX_AMT AS DECIMAL(10,2)) AS ORDH_TAX_AMT,
    CAST(ORDH_INV_AMT AS DECIMAL(10,2)) AS ORDH_INV_AMT,
    CAST(ORDH_COST_AMT AS DECIMAL(10,2)) AS ORDH_COST_AMT,

-- Dates
    -- Keep the view column typed as DATE; Python handles display formatting.
    CAST(NULLIF(CAST(ORDH_ORD_DATE AS DATE), '1900-01-01') AS DATE) AS ORDH_ORD_DATE,
    nullif(CAST(ORDH_INV_DATE AS DATE), '1900-01-01') AS ORDH_INV_DATE,
    nullif(CAST(ORDH_MOD_DATE AS DATE), '1900-01-01') AS ORDH_MOD_DATE,

-- Weight
    CAST(ORDH_TOT_WGT AS UNSIGNED) AS ORDH_TOT_WGT,

-- Customer Info
    TRIM(ORDH_CUST_NO) AS ORDH_CUST_NO,
    CAST(ORDH_TYPE_CD AS UNSIGNED) AS ORDH_TYPE_CD,
    CAST(ORDH_PMT_CD AS UNSIGNED) AS ORDH_PMT_CD,
    CAST(ORDH_INV_NO AS UNSIGNED) AS ORDH_INV_NO,
    TRIM(ORDH_CUST_NAME) AS ORDH_CUST_NAME,
    TRIM(ORDH_CUST_CITY) AS ORDH_CUST_CITY,
    TRIM(ORDH_CUST_STATE) AS ORDH_CUST_STATE,
    CAST(ORDH_CUST_ZIP AS UNSIGNED) AS ORDH_CUST_ZIP,
    TRIM(ORDH_SHIP_NAME) AS ORDH_SHIP_NAME,
    TRIM(ORDH_SHIP_CITY) AS ORDH_SHIP_CITY,
    TRIM(ORDH_SHIP_STATE) AS ORDH_SHIP_STATE,
    CAST(ORDH_SHIP_ZIP AS UNSIGNED) AS ORDH_SHIP_ZIP,
    TRIM(ORDH_PO_NUM) AS ORDH_PO_NUM,
    CAST(ORDH_SHIP_NO AS UNSIGNED) AS ORDH_SHIP_NO
FROM order_history_hdrs;