create or replace view po_history_lines_clean as 
SELECT 
-- PO IDs
    TRIM(POLNF_KEY) AS POLNF_KEY,
    CAST(POLN_POHD_KEY AS UNSIGNED) AS POLN_POHD_KEY,
    CAST(POLN_PO_NO AS UNSIGNED) AS POLN_PO_NO,
    CAST(POLN_SUB_PO_NO AS UNSIGNED) AS POLN_SUB_PO_NO,
    CAST(POLN_SEQ_NO AS UNSIGNED) AS POLN_SEQ_NO,
    CAST(POLN_PARENT_SEQ_NO AS UNSIGNED) AS POLN_PARENT_SEQ_NO,
    TRIM(POLN_VENDOR_NAME) AS POLN_VENDOR_NAME,

-- Item Info
    SUBSTRING(POLN_ITEM_NO, 1, 2) AS POLN_ITEM_CLASS_NO,
    TRIM(POLN_ITEM_NO) AS POLN_ITEM_NO,
    TRIM(SUBSTRING_INDEX(POLN_ITEM_DESC, ' ', 1)) AS POLN_ITEM_DESC_PREF,
    TRIM(POLN_ITEM_DESC) AS POLN_ITEM_DESC,
    CAST(POLN_VMI_TAG_NO AS UNSIGNED) AS POLN_VMI_TAG_NO,

-- Quantity Info
    CAST(POLN_ORDER_QTY AS UNSIGNED) AS POLN_ORDER_QTY,
    CAST(POLN_PREVRECD_QTY AS UNSIGNED) AS POLN_PREVRECD_QTY,

-- Financial Info
    CAST(POLN_ITEM_PRICE AS DECIMAL(10,2)) AS POLN_ITEM_COST,
    CAST(POLN_ITEM_COST AS DECIMAL(10,2)) AS POLN_ITEM_TOTAL_COST,
    CAST(POLN_EXT_AMT AS DECIMAL(10,2)) AS POLN_TOTAL_COST,
    CAST(POLN_RCVD_PRICE AS DECIMAL(10,2)) AS POLN_RCVD_PRICE,

-- Date Info
    CAST(POLN_DELIV_DATE AS DATE) AS POLN_DELIV_DATE,
    nullif(CAST(POLN_DATE_GOODS_RECD AS DATE), '1900-01-01') AS POLN_DATE_GOODS_RECD,

-- Location Info
    TRIM(POLN_ITEM_BIN) AS POLN_ITEM_BIN,
    TRIM(POLN_SHIPTO_LOC) AS POLN_SHIPTO_LOC,

-- Other Info
    TRIM(POLN_VEND_UOM) AS POLN_VEND_UOM,
    CAST(POLN_ITEM_CONV_FACTOR AS UNSIGNED) AS POLN_CONV_FACTOR
from po_history_lines
where POLN_ITEM_NO NOT IN ('1', 'X', 'C', 'F', 'TAG', 'SPEC', 'COIL PROCESS',
                           'WIRE16', 'WIRE14', 'WIRE14HRPO')
and substring(poln_item_no, 1, 2) between 12 and 67
and TRIM(SUBSTRING_INDEX(POLN_ITEM_DESC, ' ', 1)) not in ('**', 'COATED', 'MISCELLANEOUS', 
                                                          'BOND', 'PTD', 'ALMZ'
                                                          'CR');

select distinct poln_item_desc_pref
from po_history_lines_clean;

select * from po_history_lines_clean
where POLN_ITEM_DESC_PREF in ('HRPO', 'HPRO', 'HRP', 'HRPD', 'RHPO');


select distinct POLN_ITEM_DESC_PREF from po_history_lines_clean where POLN_ITEM_CLASS_NO = 66;