create or replace view po_history_hdrs_clean AS
SELECT 
-- PO Identifiers
    TRIM(POHDF_KEY) as POHD_KEY,

-- Numeric Information
    CAST(POHD_GROSS_AMT AS DECIMAL(18,2)) AS POHD_GROSS_AMT,
    CAST(POHD_WEIGHT AS UNSIGNED) AS POHD_WEIGHT,

-- Vendor Information
    TRIM(POHD_VEND_NO) AS POHD_VEND_NO,
    TRIM(POHD_VEND_NAME) AS POHD_VEND_NAME,
    TRIM(POHD_VEND_ADDR1) AS POHD_VEND_ADDR,
    TRIM(POHD_VEND_CITY) AS POHD_VEND_CITY,
    TRIM(POHD_VEND_STATE) AS POHD_VEND_STATE,
    CAST(POHD_VEND_ZIP AS UNSIGNED) AS POHD_VEND_ZIP,

-- Company Information
    TRIM(POHD_CO_NAME) AS POHD_CO_NAME,
    TRIM(POHD_CO_CITY) AS POHD_CO_CITY,
    TRIM(POHD_CO_STATE) AS POHD_CO_STATE,
    CAST(POHD_CO_ZIP AS UNSIGNED) AS POHD_CO_ZIP,

-- Order Information
    CAST(POHD_PO_DATE AS DATE) AS POHD_PO_DATE,
    CAST(POHD_DELIV_DATE AS DATE) AS POHD_DELIV_DATE,
    CAST(POHD_STATUS_CD AS UNSIGNED) AS POHD_STATUS_CD,

-- Other Information
    CAST(POHD_CHK_NO AS UNSIGNED) AS POHD_CHK_NO,
    CAST(POHD_BUYER_CD AS UNSIGNED) AS POHD_BUYER_CD
from po_history_hdrs
where pohd_po_no <> 1
and pohd_vend_no not in ("00000000")
and POHD_VEND_NAME not in ("* TEST PURCHASE ORDER");

select * from po_history_hdrs_clean;