create or replace view order_history_lines_clean as 
SELECT 
    CAST(ORDLF_KEY AS UNSIGNED) AS ORDLF_KEY,
    CAST(ORDLF_ORDH_KEY AS UNSIGNED) AS ORDLF_ORDH_KEY,
    CAST(ORDL_ORDER_NO AS UNSIGNED) AS ORDL_ORDER_NO,
    CAST(ORDL_SUB_ORDER_NO AS UNSIGNED) AS ORDL_SUB_ORDER_NO,
    CAST(ORDL_SEQ_NO AS UNSIGNED) AS ORDL_SEQ_NO,
    TRIM(ORDL_ITEM_NO) AS ORDL_ITEM_NO,
    TRIM(ORDL_ITEM_DESC) AS ORDL_ITEM_DESC,
    CAST(ORDL_ORDER_QTY AS UNSIGNED) AS ORDL_ORDER_QTY,
    CAST(ORDL_ITEM_PRICE AS DECIMAL(10,2)) AS ORDL_ITEM_PRICE,
    CAST(ORDL_ITEM_COST AS DECIMAL(10,2)) AS ORDL_ITEM_COST,
    CAST(ORDL_EXT_AMT AS DECIMAL(10,2)) AS ORDL_EXT_AMT,
    CAST(ORDL_EXT_COST AS DECIMAL(10,2)) AS ORDL_EXT_COST,
    TRIM(ORDL_ITEM_UOM) AS ORDL_ITEM_UOM,
    TRIM(ORDL_ITEM_BIN) AS ORDL_ITEM_BIN,
    CAST(ORDL_PRICE_CD AS UNSIGNED) AS ORDL_PRICE_CD,
    CAST(ORDL_GLACCT AS UNSIGNED) AS ORDL_GLACCT,
    CAST(ORDL_CONV_FACTOR AS DECIMAL(10,2)) AS ORDL_CONV_FACTOR,
    CAST(ORDL_ITEM_CLASS AS UNSIGNED) AS ORDL_ITEM_CLASS,
    TRIM(ORDL_VENDOR) AS ORDL_VENDOR,
    CAST(ORDL_WHSE_NO AS UNSIGNED) AS ORDL_WHSE_NO,
    TRIM(ORDL_LOT_NO) AS ORDL_LOT_NO,
    CAST(ORDL_PARENT_SEQ_NO AS UNSIGNED) AS ORDL_PARENT_SEQ_NO,
    TRIM(ORDL_CUST_NO) AS ORDL_CUST_NO,
    CAST(ORDL_VMIT_TAG_NO AS UNSIGNED) AS ORDL_VMIT_TAG_NO,
    CAST(ORDL_SKID_TAG_NO AS UNSIGNED) AS ORDL_SKID_TAG_NO
from order_history_lines 
where TRIM(ORDL_ITEM_NO) NOT IN ('C', 'F', 'EXPORT');

