create or replace view po_history_lines_clean as 
SELECT 
    TRIM(POLNF_KEY) AS POLNF_KEY,
    CAST(POLN_POHD_KEY AS UNSIGNED) AS POLN_POHD_KEY,
    CAST(POLN_PO_NO AS UNSIGNED) AS POLN_PO_NO,
    CAST(POLN_SUB_PO_NO AS UNSIGNED) AS POLN_SUB_PO_NO,
    CAST(POLN_SEQ_NO AS UNSIGNED) AS POLN_SEQ_NO,
    TRIM(POLN_ITEM_NO) AS POLN_ITEM_NO,
    CAST(POLN_ORDER_QTY AS UNSIGNED) AS POLN_ORDER_QTY,
    CAST(POLN_REC_QTY AS UNSIGNED) AS POLN_REC_QTY,
    CAST(POLN_PREVRECD_QTY AS UNSIGNED) AS POLN_PREVRECD_QTY,
    TRIM(POLN_ITEM_DESC) AS POLN_ITEM_DESC,
    CAST(POLN_ITEM_PRICE AS DECIMAL(10,2)) AS POLN_ITEM_PRICE,
    CAST(POLN_ITEM_COST AS DECIMAL(10,2)) AS POLN_ITEM_COST,
    CAST(POLN_EXT_AMT AS DECIMAL(10,2)) AS POLN_EXT_AMT,
    TRIM(POLN_ITEM_BIN) AS POLN_ITEM_BIN,
    CAST(POLN_DELIV_DATE AS DATE) AS POLN_DELIV_DATE,
    CAST(POLN_GLACCT AS UNSIGNED) AS POLN_GLACCT,
    TRIM(POLN_VEND_UOM) AS POLN_VEND_UOM,
    CAST(POLN_ITEM_CONV_FACTOR AS UNSIGNED) AS POLN_ITEM_CONV_FACTOR,
    CAST(POLN_DATE_GOODS_RECD AS DATE) AS POLN_DATE_GOODS_RECD,
    CAST(POLN_PARENT_SEQ_NO AS UNSIGNED) AS POLN_PARENT_SEQ_NO,
    TRIM(POLN_VENDOR_NAME) AS POLN_VENDOR_NAME,
    TRIM(POLN_SHIPTO_LOC) AS POLN_SHIPTO_LOC,
    CAST(POLN_RCVD_PRICE AS DECIMAL(10,2)) AS POLN_RCVD_PRICE,
    CAST(POLN_VMI_TAG_NO AS UNSIGNED) AS POLN_VMI_TAG_NO,
    CAST(POLN_PRINT_COLOR_CD AS UNSIGNED) AS POLN_PRINT_COLOR_CD
from po_history_lines
where POLN_ITEM_NO NOT IN ('C', 'F');
